ruby '2.2.3'
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'

gem 'pg'
gem 'rails-api'
gem 'devise'
gem 'acts-as-taggable-on'
gem 'active_model_serializers', '~> 0.8.3'
gem 'rack-cors', require: 'rack/cors'
